name: Autotag & Release
on:
  push:
    branches:
      - main
jobs:
  tag-release:
    runs-on: ubuntu-latest
    name: Tag & Release
    steps:
      - name: Checkout
        uses: actions/checkout @v3
      - name: Tag & Release
        run: bash ./bin/tag-release.sh
        with:
          gh-token: ${{ github.token }}